// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Article { id: string, title: string, url: string, cover: string | null, contents: string, }